### PR TITLE
fix control visibility setting

### LINKED ISSUE #240: Controls can't be set to minimized initially.
# Test notes
* Define each of three control visibility settings: `{controlVisibility: 'visible'}`, `{controlVisibility: 'minimized'}`, and `{controlVisibility: 'disabled'}`.
* Verify that the controls display appropriately when the codebook initializes.
* Verify that changing tabs, specifically to the _Settings_ tab, does not alter the visibility of the controls, except to hide the controls on the _Settings_ tab.

### PR DESCRIPTION
**Pull request by samussiah**
# Issues
Closes #240

### CODE REVIEW

**Comment by danedexF5** [comment]
@jwildfire minimizing and disabling setting works as expected in 3 browsers. Is {controlVisibility: 'visible'} the default? What is the "Settings" tab exactly? Is it the "Codebook" tab? If so, this passes for me.

**Comment by jwildfire** [comment]
screen shot 2018-05-22 at 6 06 04 am

@danedexF5 The settings tag can be accessed using the gear icon on the far right of the nav bar. (It's not the same as the codebook tab)

**Comment by danedexF5** [comment]
@jwildfire I'm able to toggle between tabs including Settings. When on Settings, the controls do not Hide though, they are just disabled. They do become visible once a different tab is selected.

**Comment by jwildfire** [comment]
@danedexF5 The controls should be hidden (not, visible + disabled) on the settings page. Which test page are you using? Seems to work for me in CAT

**Comment by danedexF5** [comment]
@jwildfire In CAT with FF, see screenshot: 

settingsnocontrols

**Pull request merged**
