### PR TITLE
V1.1 dev

### PR DESCRIPTION
**Pull request by jwildfire**

### CODE REVIEW

**Comment by jwildfire** [comment]
@brittsikora Feature development is all done. Release candidate `v1.1-RC1` is tagged and ready for regression testing.

**Comment by brittsikora** [comment]
Codebook Regression Tests
  
Navigation and Settings
[x] Confirm that the codebook has the following navigation options: codebook, data listing, and settings
[x] Confirm that checking a box under “Hidden” within the “Settings” hides the data column by default in both the “Codebook” and “Data Listing” views
[x] Confirm that checking a box under “Filter” within the “Settings” adds the column variable to the available filters
[x] Confirm that checking a box under “Group” within the “Settings” adds the column variable to the list of options in the group by drop-down
[x] Confirm that unchecking a box under “Hidden” within the “Settings” results in the data column being displayed again in both the “Codebook” and “Data Listing” views
[x] Confirm that unchecking a box under “Filter” within the “Settings” removes the column variable from the available filters
[x] Confirm that unchecking a box under “Group” within the “Settings” removes the column variable from the list of options in the group by drop-down
[x] Confirm that manipulating the filters and grouping by variables prompts the loading indicator to appear
 
Chart header
[x] Confirm that the number of variable data columns cited matches the number of variables provided in the data set
[ ] Confirm that the number of columns displayed in the current view is correct by counting the number of variables listed in the data summary
[x] Confirm that the number and percentage of data rows displayed in the current view is working correctly by using a filter and noting a change in the number and percentage of rows shown 
[x] Confirm that an error message displays if you filter the data down to values that do not match any data points
 
Variables
[x] Confirm that there is metadata provided for each variable. Variable name should appear for each measure, its type should appear to the right of the variable name, and below those, the  most frequent values in the data set should render
[ ] Confirm that "N", "n", "Missing", and "Unique" render to the right of each categorical variable name 
[x] Confirm that  "N", "n", "Missing", "mean", "SD", and "median" render to the right of each continuous variable name
[x] Expand  variable rows by clicking on the grey arrow beside the variable ID
[x] Collapse variable rows by clicking on the grey arrow beside the variable ID
[x] Confirm that horizontal bar charts are being displayed for categorical variables with 5 or fewer levels. Confirm that these charts display an x-axis
[x] Confirm that vertical bar charts are being displayed for categorical variables with more than 5 levels. Confirm that these charts do not display an x-axis
[x] Confirm that the "Summarize by" drop-down is working correctly for categorical variables and offers the options: "rate" and "frequency"
[x] Confirm that the “Sort levels” drop down is working correctly for vertical bar charts and offers the options: “Alphabetical”, “Ascending”, and “Descending”
[x] Confirm that a histogram chart renders for continuous variables
 
Filters and Controls
[x] Confirm that selecting the Hide button to the right of "Codebook Controls" hides the controls menu
[x] Confirm that selecting the Show button to the right of "Codebook Controls" shows the controls menu
[x] Confirm that all chart types are behaving as expected when using the “group by” control
[x] Confirm that the "Display Type" drop-down is working correctly for horizontal bar charts when the user groups the data by a variable and offers the options: "Paneled (Bar Charts)" or "Grouped (Dot Plot)"
[x] Change the input on the data filters, confirm the chart updates 
[x] Confirm that clicking “Show all charts” opens a chart for each variable
[x] Confirm that clicking “Hide all charts” closes each variable’s chart
 
Hover
[x] Hover over a vertical bar to confirm it displays metadata (n and an additional variable)
[ ] Hover over a horizontal bar to confirm it displays metadata (variable, n, percent, and number and line corresponding to difference from overall rate)
[x] Hover over a grouped dot plot to confirm it displays metadata (variable, n, and percent)
[x] Hover over a histogram to confirm it displays metadata (n and range)
[x] Hover over one of the data values listed underneath a categorical variable name to confirm that the n is displayed
[x] Hover over the "…" in a variable with continuous data to confirm that it displays the number of values not shown

Data Listing
[x] Change the input on the data filters, confirm that the listing updates  
[x] Click a column header to confirm that it sorts the data values
[x] Click the “x” on the sorted column name box and confirm that the box disappears
[x] Confirm pagination is listed at the bottom of the page and the page links work
[x] Type a value into the search box and confirm that the data listing updates
[x] Delete the entered value from the search bar and confirm that the data listing resets

**Comment by brittsikora** [comment]
I found the following issues:
- Unique variable not listed for categorical variables (known issue)
- When columns are hidden, the data summary doesn't update with the new number of columns (known issue)
- In IE, horizontal bar charts do not have the mean comparison line on hover

**Comment by brittsikora** [comment]
Codebook Regression Tests

[x] Confirm that the number of columns displayed in the current view is correct by counting the number of variables listed in the data summary
[x] Confirm that "N", "n", "Missing", and "Unique" render to the right of each categorical variable name

**Pull request merged**
