### PR TITLE
Settings schema

### LINKED ISSUE #245: Add settings schema.
# Test Notes

Confirm that the form view of the settings object is available in CAT.

### PR DESCRIPTION
**Pull request by samussiah**
# Issues
Closes #245

### CODE REVIEW

**Comment by danedexF5** [comment]
@jwildfire Not sure how to test this one?

**Comment by jwildfire** [comment]
The form section of the page in CAT should appear if the schema is working correctly. Unfortunately, it's not working now. It looks like there is a bug that @samussiah or I will need to figure out.

**Comment by jwildfire** [comment]
screen shot 2018-05-31 at 4 48 42 am

Looks like my attempt at a quick fix failed ... @samussiah Any idea what's going on here?

**Comment by jwildfire** [comment]
Bug was because the form maker in CAT didn’t like a schema setting with type=array with no `items` associated. Merging to v1.4-dev now.

**Pull request merged**
